### ISSUE TITLE
Add import / export cv settings as json 

### ISSUE THREAD

**Issue by slzakaria** [Zackaria-Slimane/cvforge#1]
Fetch the cv data as json and add a features to be able to import and export those settings.
The buttons are already in place

**Comment by MohdSaquib114** [comment]
Hey @Zackaria-Slimane  can you please describe more about this issue.

**Comment by slzakaria** [comment]
> Hey @Zackaria-Slimane can you please describe more about this issue.

Hey there , so the way the application works is it saves the data along the way users filling inputs, and the idea is the be able to export the data as json on the button click. 

The data is already there and saved in local storage, you just have to write code to export it and import json data and fill in the application.

**Comment by MohdSaquib114** [comment]
So we have to send the data fill by the user on the front-end to the backend sever

**Comment by slzakaria** [comment]
> So we have to send the data fill by the user on the front-end to the backend sever

There's no need for a backend server considering it's current features. The data is already saved on local storage and front end, you just need a way to make it downloadable as json.

**Comment by MohdSaquib114** [comment]
Okay, I will try on it  give it some time and if  i solve this than inform you about it. Thanks a lot for helping out to me @Zackaria-Slimane .

**Comment by MohdSaquib114** [comment]
@Zackaria-Slimane ,  i implemented  the export button functionality. I use the blob constructer to convert it into blob file and then use the anchor tag "a" to make it download on the user machine.


```
	function downloadJSONSettings(setting) {
		
		const jsonSetting = JSON.stringify(setting);
		const blobSetting = new Blob([jsonSetting], { type: 'application/json' });
		const url = URL.createObjectURL(blobSetting);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'data.json';
		a.click();
		URL.revokeObjectURL(url);
	}

//Handle Function used in export onClick function
	const exportSettings = () => {
      downloadJSONSettings(sharedData)
	}
```

**Comment by slzakaria** [comment]
> @Zackaria-Slimane , i implemented the export button functionality. I use the blob constructer to convert it into blob file and then use the anchor tag "a" to make it download on the user machine.
> 
> ```
> 	function downloadJSONSettings(setting) {
> 		
> 		const jsonSetting = JSON.stringify(setting);
> 		const blobSetting = new Blob([jsonSetting], { type: 'application/json' });
> 		const url = URL.createObjectURL(blobSetting);
> 		const a = document.createElement('a');
> 		a.href = url;
> 		a.download = 'data.json';
> 		a.click();
> 		URL.revokeObjectURL(url);
> 	}
> 
> //Handle Function used in export onClick function
> 	const exportSettings = () => {
>       downloadJSONSettings(sharedData)
> 	}
> ```

Perfect ! the code works , you can go ahead and open pull request so i can include your work :)

**Comment by MohdSaquib114** [comment]
But @Zackaria-Slimane  there's a question about the import functionality : 
How would user give back the json setting as their is no input for submitting back the json setting

**Comment by MohdSaquib114** [comment]
that's why  i only implemented the export functionality

**Comment by slzakaria** [comment]
> But @Zackaria-Slimane  there's a question about the import functionality : 
> 
> How would user give back the json setting as their is no input for submitting back the json setting

Sorry, my bad i thought you only wanted to do the export.
For the import, you will need a input type of file , and a library or function to read the json file and set sharedData to that files content

**Comment by MohdSaquib114** [comment]
SO, can i make pull request for only export functionality.

**Comment by slzakaria** [comment]
> SO, can i make pull request for only export functionality.

Yes you can if that is what you want , and then later work on import if you feel like it

**Comment by MohdSaquib114** [comment]
Ok, then i will work on the import later. Right now i m  going to make a pr.
